# Generated by Django 2.1.3 on 2018-11-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181113_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='text',
        ),
    ]
